# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: 12.x 
        
    - name: Install Yarn
      run: 'npm install -g yarn@1.22.4'
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-scripts

    - name: Build
      run: yarn build && yarn tarball
    
    - name: Test
      run: yarn run mocha
    
    - name: Smoketest NodeJS/Typescript
      run: yarn smoketest
    
    - name: Smoketest create-react-app/Typescript
      run: |
        cd examples/website
        yarn install
        yarn build
